apiVersion: v1
kind: Pod
metadata:
  name: geth-mainnet
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: geth-default
  containers:
    - name: geth-mainnet
      image: gcr.io/hanzo-ai/geth:latest
      resources:
        requests:
          cpu: 8
          memory: 8Gi
      command:
        - /go-ethereum/build/bin/geth
      args:
        - --datadir=/data
        - --cache=4096
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=13264
        - --syncmode=fast
        - --maxpeers=50
        - --rpccorsdomain="*"
      volumeMounts:
        # - mountPath: '/ethereum'
        #   name: geth-mainnet-pv
        - mountPath: '/data'
          name: geth-mainnet-data-pv
  volumes:
    # - name: geth-mainnet-pv
    #   persistentVolumeClaim:
    #     claimName: geth-mainnet-pvc
    - name: geth-mainnet-data-pv
      persistentVolumeClaim:
        claimName: geth-mainnet-data-pvc
