apiVersion: v1
kind: Pod
metadata:
  name: geth-mainnet
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: geth-default
  containers:
    - name: geth-mainnet
      image: gcr.io/hanzo-ai/geth:latest
      resources:
        requests:
          cpu: 8
          memory: 8Gi
      command:
        - /bin/geth
      args:
        - --datadir=/data
        - --ethash.dagdir=/data/geth/chaindata/dag
        - --cache=4096
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=13264
        - --syncmode=fast
        - --maxpeers=50
        - --rpccorsdomain="*"
      volumeMounts:
        - mountPath: '/data/geth/chaindata'
          name: geth-mainnet-pv
  volumes:
    - name: geth-mainnet-pv
      persistentVolumeClaim:
        claimName: geth-mainnet-pvc
