apiVersion: v1
kind: Pod
metadata:
  name: geth-mainnet-000
  network: mainnet
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: geth-mainnet
  containers:
    - name: geth-mainnet-000
      image: gcr.io/hanzo-ai/geth:latest
      resources:
        requests:
          cpu: 3
          memory: 8Gi
      command:
        - /bin/geth
      args:
        - --datadir=/data
        - --ethash.dagdir=/data/geth/chaindata/dag
        - --cache=4096
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=8545
        - --rpccorsdomain="*"
        - --ws
        - --wsaddr=0.0.0.0
        - --wsport=8546
        - --wsorigins="*"
        - --syncmode=fast
        - --maxpeers=50
      volumeMounts:
        - mountPath: '/data/geth/chaindata'
          name: geth-mainnet-000-pv
  volumes:
    - name: geth-mainnet-000-pv
      gcePersistentDisk:
        pdName: geth-mainnet-000-pd
        fsType: ext4
