apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-mainnet-pvc
spec:
  storageClassName: gce-ssd-sc
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 500G
