apiVersion: v1
kind: Pod
metadata:
  name: geth-testnet
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: geth-default
  containers:
    - name: geth-testnet
      image: gcr.io/hanzo-ai/geth:latest
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 2
          memory: 6Gi
      command:
        - /bin/geth
      args:
        - --datadir=/data
        - --ethash.dagdir=/data/geth/chaindata/dag
        - --cache=2048
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=13264
        - --syncmode=fast
        - --maxpeers=25
        - --rpccorsdomain="*"
        - --testnet
      volumeMounts:
        - mountPath: '/data/geth/chaindata'
          name: geth-testnet-data-pv
  volumes:
    # - name: geth-testnet-pv
    #   persistentVolumeClaim:
    #     claimName: geth-testnet-pvc
    - name: geth-testnet-data-pv
      persistentVolumeClaim:
        claimName: geth-testnet-data-pvc
