apiVersion: v1
kind: Pod
metadata:
  name: geth-testnet-000
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  containers:
    - name: geth-testnet-000
      image: gcr.io/hanzo-ai/geth:latest
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
      command:
        - /bin/geth
      args:
        - --datadir=/data
        - --ethash.dagdir=/data/geth/chaindata/dag
        - --cache=1024
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=8545
        - --rpccorsdomain="*"
        - --ws
        - --wsaddr=0.0.0.0
        - --wsport=8546
        - --wsorigins="*"
        - --syncmode=fast
        - --maxpeers=25
        - --testnet
      volumeMounts:
        - mountPath: '/data/geth/chaindata'
          name: geth-testnet-000-pv
  volumes:
    - name: geth-testnet-000-pv
      gcePersistentDisk:
        pdName: geth-testnet-000-pd
        fsType: ext4
