apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-testnet-pvc
spec:
  storageClassName: ssd-retain-sc
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 500G
