apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUt1TkNnZEQwYVFSSlpIOUlMS3VrY1F3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lXRTFaVGswWXpFdE9EZGtNeTAwWkdVMExUaGxaV010TnpsaE1tSTFaRE0wTmpWaApNQjRYRFRFNE1EUXdNakl4TkRRME5sb1hEVEl6TURRd01USXlORFEwTmxvd0x6RXRNQ3NHQTFVRUF4TWtZV0UxClpUazBZekV0T0Rka015MDBaR1UwTFRobFpXTXROemxoTW1JMVpETTBOalZoTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd0RWU01JTDBjVGt6bThWd1pnSDhTc3NRNFdWdWUyQXRHcGRicTV6VQpBRlBMWHFpUXFKUHVPUzBlYkt6WVhIYzlWMXdHdkg0M2phWnF2UXFNb1NMMlZRZzZTRGpaTDdVdmVYbUhxRUthCm9oV0VySGl2Nmp6TnBiYm1pRVQ5WEYzNDByTVVsUm5Pa25oY1VzWU9SWEhDdDRIZHNUUkR5NjhPUXRmdmx2RmsKei96UlpteHdFNFZYK1NIOVlRZ1ZVUUZBTExKVlNCSjBuZkpYczdlZUgrblNKMVp4TlVKTVZnbTZyQ3BsUzZtdQpyNUw2U2VpRWZpeGFmbGUyTTNlZXRWa3Q1cHZQL2lPckQ5VXV3ZW01ZWVXTGZPQ0RHcnk5RndqaFMvbUZIUXFtCjBBUnpySW1VSDdDemRReWhDTXdNLzNrZFBkMWZwbVVCRnUzOVExK0kyZVFpUFFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpHWW5IbGRjZ281VEpNVnNCeGw5bWlKZnJiaHAxUDExV1NFVkhraVdTY0lGc3U5Z3puNnRHOVZnQXZkK1pkT21zCmVJOHBHYXlkMmtqNGVCd1psaHRsMXYydytPR2dWSTA3U3Z0V2pTV0N0RGNaUTRYSGNTTTk4TGxKeCsySDkvRW4KMktUa0VBWG01Q1MyL3IrQ3QrZ1h5cld1bmJKYTRpa3FMNkNDTGlOdk1jbngzd0Fjc3BmK0hxd09kTjVNcWI0NAppRG1RTDVHejFVcGRCY010a20rOVdZdGRLZTNZQ2NqaWNPRXhTbUNjY2pzOGhMNXB0YWkxbXNMYngwZ1BGMElECmFRZTF2VE00SmNVeGd1cHhOcUxDaVo3TG1aejhob0s3K0d6RkptbSs0MHBCay9mSEo3OW05c0lFN1FrTXREeHAKYzlNRGdlSWRsTWxSRndWRzdBSTdQZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.188.203.215
  name: gke_hanzo-ai_us-central1-a_ethereum
contexts:
- context:
    cluster: gke_hanzo-ai_us-central1-a_ethereum
    user: gke_hanzo-ai_us-central1-a_ethereum
  name: gke_hanzo-ai_us-central1-a_ethereum
current-context: gke_hanzo-ai_us-central1-a_ethereum
kind: Config
preferences: {}
users:
- name: gke_hanzo-ai_us-central1-a_ethereum
  user:
    auth-provider:
      config:
        access-token: ya29.GlzvBgXYo06yvavGrjZyT92AR4rDO6GTF-Y33PDNrxVn2Xln4nL9l9sCdZP4Ua8xNGax44da-jO8LZl3AODMA62Sab1XMqg_oFEaQFiHOKfF4fKljfMAS6A2b_hTrA
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: 2019-04-18T17:42:21Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
