apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-ss
spec:
  selector:
    matchLabels:
      app: geth-testnet
  serviceName: "geth-testnet"
  replicas: 10 # by default is 1
  template:
    metadata:
      labels:
        app: geth-testnet
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: geth-testnet
        image: gcr.io/hanzo-ai/geth:latest
        command:
          - /go-ethereum/build/bin/geth
        args:
          - --datadir=/ethereum
          - --cache=1024
          - --rpc
          - --rpcaddr=0.0.0.0
          - --rpcport=13264
          - --syncmode=fast
          - --rpccorsdomain="*"
      volumeMounts:
        - mountPath: '/ethereum'
          name: geth-testnet-pv
  volumeClaimTemplates:
  - metadata:
      name: geth-testnet-storage
    spec:
      accessModes: [ "ReadOnlyMany" ]
      storageClassName: geth-storage
      resources:
        requests:
          storage: 1000Gi
